version: "3"
   
services:
  hexa-server:
    container_name: hexa-server
    image: 749960970623.dkr.ecr.ap-northeast-2.amazonaws.com/hexa-server
    restart: always
    command: python app.py
  nginx:
    container_name: nginx
    image: 749960970623.dkr.ecr.ap-northeast-2.amazonaws.com/hexa-server-nginx
    restart: always
    ports:
        - "80:80"
    environment:
        - TZ=Asia/Seoul
    logging:
        driver: none